# Tabular Playground Series - Oct 2021

#### Oct 01, 2021 to Oct 31, 2021

#### https://www.kaggle.com/c/tabular-playground-series-oct-2021/

#### _**Predicting the biological response of molecules given various chemical properties**_

Notebook Author:

| Name  | Pradip Kumar Das  |
| ------------: | :------------ |
| **Profile:**  | [LinkedIn](https://www.linkedin.com/in/daspradipkumar/ "LinkedIn") l [GitHub](https://github.com/PradipKumarDas "GitHub") l [Kaggle](https://www.kaggle.com/pradipkumardas "Kaggle")  |
| **Contact:**  | pradipkumardas@hotmail.com (Email)  |
| **Location:**  | Bengaluru, India  |

**Sections:**

* Dependencies
* Exploratory Data Analysis (EDA) & Preprocessing
* Modeling & Evaluation
* Submission

## Dependencies

In [1]:
# Loads required packages

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.metrics import roc_auc_score

from xgboost import XGBClassifier
import xgboost as xgb

from hyperopt import hp, fmin, tpe, Trials, STATUS_OK

## Exploratory Data Analysis (EDA) & Preprocessing

In [2]:
# Loads train dataset
train = pd.read_csv("../input/tabular-playground-series-oct-2021/train.csv")

In [3]:
# Checks how the train data set looks
with pd.option_context('display.max_rows', 10, 'display.max_columns', None): 
    display(train)

id        f0        f1        f2        f3        f4        f5  \
0            0  0.205979  0.410993  0.176775  0.223581  0.423543  0.476140   
1            1  0.181004  0.473119  0.011734  0.213657  0.619678  0.441593   
2            2  0.182583  0.307431  0.325950  0.207116  0.605699  0.309695   
3            3  0.180240  0.494592  0.008367  0.223580  0.760618  0.439211   
4            4  0.177172  0.495513  0.014263  0.548819  0.625396  0.562493   
...        ...       ...       ...       ...       ...       ...       ...   
999995  999995  0.204312  0.344754  0.262267  0.228333  0.610727  0.357463   
999996  999996  0.182004  0.564019  0.242564  0.241178  0.453623  0.469513   
999997  999997  0.250304  0.491553  0.098547  0.235656  0.771272  0.368018   
999998  999998  0.203572  0.534923  0.180118  0.213109  0.654544  0.535152   
999999  999999  0.160972  0.596308  0.013061  0.280355  0.579849  0.401904   

              f6        f7        f8        f9       f10       f11       f12  \
0       0.413590  0.612021  0.534873  0.147295  0.026177  0.106613  0.200924   
1       0.230407  0.686013  0.281971  0.238509  0.493411  0.107277  0.231828   
2       0.493337  0.751107  0.536272  0.286813  0.139532  0.107222  0.247791   
3       0.432055  0.776147  0.483958  0.260886  0.147122  0.105433  0.287755   
4       0.117158  0.561255  0.077115  0.158321  0.260239  0.102561  0.265285   
...          ...       ...       ...       ...       ...       ...       ...   
999995  0.490586  0.613655  0.509203  0.160930  0.262791  0.631298  0.327143   
999996  0.477518  0.659226  0.519219  0.252664  0.151836  0.107096  0.250046   
999997  0.531642  0.598111  0.618474  0.349413  0.146687  0.105224  0.201161   
999998  0.316271  0.652522  0.398026  0.252192  0.010743  0.104855  0.291573   
999999  0.493870  0.611947  0.531370  0.269219  0.148062  0.101005  0.259814   

             f13       f14       f15       f16       f17       f18       f19  \
0       0.713191  0.155750  0.557335  0.341702  0.285720  0.230396  0.203957   
1       0.457150  0.395200  0.617088  0.459358  0.209225  0.201098  0.199383   
2       0.631949  0.347463  0.642173  0.257763  0.162548  0.327377  0.193583   
3       0.455777  0.247971  0.616628  0.335907  0.337025  0.239127  0.176163   
4       0.503776  0.269776  0.545945  0.319548  0.278538  0.214922  0.200239   
...          ...       ...       ...       ...       ...       ...       ...   
999995  0.541911  0.277571  0.582371  0.322029  0.171293  0.196608  0.213131   
999996  0.615979  0.396692  0.538448  0.304368  0.215488  0.202722  0.231195   
999997  0.461524  0.453123  0.621385  0.361558  0.238448  0.196454  0.197983   
999998  0.657054  0.371032  0.518749  0.401528  0.184174  0.189672  0.216462   
999999  0.533765  0.181192  0.665614  0.313516  0.245447  0.206980  0.195957   

             f20       f21  f22       f23       f24       f25       f26  \
0       0.509588  0.706972    1  0.007793  0.247765  0.263750  0.259555   
1       0.366578  0.585788    1  0.285311  0.400367  0.162493  0.249365   
2       0.495440  0.636742    0  0.007133  0.309747  0.221081  0.284810   
3       0.538269  0.706468    1  0.008829  0.353799  0.219977  0.266858   
4       0.534551  0.728652    0  0.004840  0.323546  0.166292  0.285516   
...          ...       ...  ...       ...       ...       ...       ...   
999995  0.497520  0.683594    0  0.273762  0.339086  0.388890  0.237183   
999996  0.451034  0.699873    1  0.006190  0.467464  0.176998  0.330839   
999997  0.440465  0.753770    1  0.005730  0.323028  0.264435  0.240686   
999998  0.479028  0.739938    0  0.671710  0.207771  0.199325  0.271526   
999999  0.464070  0.571638    1  0.008868  0.229109  0.252599  0.194098   

             f27       f28       f29       f30       f31       f32       f33  \
0       0.231730  0.138379  0.197824  0.054392  0.194153  0.281500  0.034818   
1       0.141160  0.133688  0.247906  0.139251  0.216444  0.109674  0.033018   
2       0.23

In [7]:
# Drops ID column as it is not required
train.drop(["id"], axis=1, inplace=True)

In [4]:
# Checks for data types used in the data set
train.dtypes.unique()

array([dtype('int64'), dtype('float64')], dtype=object)

In [5]:
# Checks for nubmer of row having any missing values ('0' indicates no rows have missing values)
sum(train.isna().sum())

0

In [6]:
def reduce_mem_usage(df):
    """ iterate through all the columns of a dataframe and modify the data type
        to reduce memory usage.        
    """
    start_mem = df.memory_usage().sum() / 1024**2
    print('Memory usage of dataframe is {:.2f} MB'.format(start_mem))
    
    for col in df.columns:
        col_type = df[col].dtype
        
        if col_type != object:
            c_min = df[col].min()
            c_max = df[col].max()
            if str(col_type)[:3] == 'int':
                if c_min > np.iinfo(np.int8).min and c_max < np.iinfo(np.int8).max:
                    df[col] = df[col].astype(np.int8)
                elif c_min > np.iinfo(np.int16).min and c_max < np.iinfo(np.int16).max:
                    df[col] = df[col].astype(np.int16)
                elif c_min > np.iinfo(np.int32).min and c_max < np.iinfo(np.int32).max:
                    df[col] = df[col].astype(np.int32)
                elif c_min > np.iinfo(np.int64).min and c_max < np.iinfo(np.int64).max:
                    df[col] = df[col].astype(np.int64)  
            else:
#                 if c_min > np.finfo(np.float16).min and c_max < np.finfo(np.float16).max:
#                     df[col] = df[col].astype(np.float16)
#                 el
                if c_min > np.finfo(np.float32).min and c_max < np.finfo(np.float32).max:
                    df[col] = df[col].astype(np.float32)
                else:
                    df[col] = df[col].astype(np.float64)
        else:
            df[col] = df[col].astype('category')

    end_mem = df.memory_usage().sum() / 1024**2
    print('Memory usage after optimization is: {:.2f} MB'.format(end_mem))
    print('Decreased by {:.1f}%'.format(100 * (start_mem - end_mem) / start_mem))
    
    return df

In [8]:
# Compresses the training data as Kaggle kernel resets due to large size of the training data 
train = reduce_mem_usage(train)

Memory usage of dataframe is 2182.01 MB
Memory usage after optimization is: 959.40 MB
Decreased by 56.0%


In [9]:
# Shows the column data types after data compression
train.dtypes

f0        float32
f1        float32
f2        float32
f3        float32
f4        float32
           ...   
f281         int8
f282         int8
f283         int8
f284         int8
target       int8
Length: 286, dtype: object

In [10]:
# Checks distribution of categorical target variable
train.target.value_counts()

1    500485
0    499515
Name: target, dtype: int64

**As `target` is equaly distributed, it itself can be used as bins in stratified K-Fold validation**

## Modeling & Evaluation

In [11]:
# Seperates predictor variables from target

y = train.target
train.drop(["target"], axis=1, inplace=True)

In [12]:
# Create stratification object for K-Fold cross validation
sk_fold = StratifiedKFold(n_splits=5)

In [13]:
# Performs cross validation on XGB Classifier

cv_generator = sk_fold.split(train, y)

model = XGBClassifier(
    n_estimators=100,
    objective='binary:logistic', 
    eval_metric='auc',
    tree_method='gpu_hist'
)

cv_scores = cross_val_score(model, train, y, scoring='roc_auc', cv=cv_generator, n_jobs=-1, verbose=10)

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done   1 tasks      | elapsed:   35.6s
[Parallel(n_jobs=-1)]: Done   3 out of   5 | elapsed:  1.0min remaining:   41.3s
[Parallel(n_jobs=-1)]: Done   5 out of   5 | elapsed:  1.3min remaining:    0.0s
[Parallel(n_jobs=-1)]: Done   5 out of   5 | elapsed:  1.3min finished


In [14]:
print("ROC AUC score of XGBoost (with default parameters) Model:", cv_scores.mean())

ROC AUC score of XGBoost (with default parameters) Model: 0.8510695329013235


In [15]:
del cv_scores, model, cv_generator

/opt/conda/lib/python3.7/site-packages/xgboost/sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/opt/conda/lib/python3.7/site-packages/xgboost/sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[CV]  ................................................................
[CV] .................................... , score=0.851, total=  33.3s
[CV]  ................................................................
[CV] .................................... , score=0.849, total=  26.4s
[CV]  ................................................................
[CV] .................................... , score=0.853, total=  33.3s
[CV]  ................................................................
[CV] .................................... , score=0.853, total=  26.2s
[CV]  ................................................................
[CV] .................................... , score=0.849, total=  13.1s


/opt/conda/lib/python3.7/site-packages/xgboost/sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/opt/conda/lib/python3.7/site-packages/xgboost/sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/opt/conda/lib/python3.7/site-packages/xgboost/sklearn.py:1146: UserWarning: The use of label encode

**Automated Hyperparameter Tuning with Hyperopt**

In [22]:
# Instead of performing cross validation during hyperparameter tunining, 
# the tuning is done over fixed train and validation data set to save significant amount of time
# The following code snippet extract that stratified set of train and validation set

cv_generator = sk_fold.split(train, y)

for fold, (idx_train, idx_val) in enumerate(cv_generator):
    y_val = y.iloc[idx_val]
    dtrain = xgb.DMatrix(data=train.iloc[idx_train], label=y.iloc[idx_train])
    dval = xgb.DMatrix(data=train.iloc[idx_val], label=y.iloc[idx_val])
    break

In [18]:
# Sets up a search space for XGBoost hyperparameters
space = {
    'learning_rate': hp.uniform('learning_rate', 0.01, 0.3),
    'max_depth': hp.quniform("max_depth", 2, 6, 1),
    'min_child_weight' : hp.quniform('min_child_weight', 1, 8, 1),
    'reg_alpha' : hp.uniform('reg_alpha', 1e-8, 100),
    'reg_lambda' : hp.uniform('reg_lambda', 1e-8, 100),
    'gamma': hp.uniform ('gamma', 0.0, 1.0),
    'subsample': hp.uniform("subsample", 0.1, 1.0),
    'colsample_bytree': hp.uniform('colsample_bytree', 0.1, 1.0)
}

In [28]:
def trial_loss(space):
    """
    Trial function for Hyperopt to call by passing a set a trial hyperparamets
    to train model and perform predictions.
    
    Parameters:
    ----------
    space: A set a trial hyperparamets
    
    Returns metric for Hyperopt to estimate for further tuning in search space.
    """
    
    # Converts parameter value to int as required by XGBoost
    space["max_depth"] = int(space["max_depth"])
    space["objective"] = "binary:logistic"
    space["eval_metric"] = "auc"
    space["tree_method"] = "gpu_hist"
    
    model = xgb.train(
        space, 
        dtrain, 
        num_boost_round=2000, 
        evals=[(dtrain, 'train'), (dval, 'eval')],
        early_stopping_rounds=50, verbose_eval=False)
    
    predictions = model.predict(dval)
    
    roc_auc = roc_auc_score(y_val, predictions)
    
    del predictions, model, space
    
    return {"loss": -roc_auc, "status": STATUS_OK}

In [29]:
# Starts hyperparameters tuning
trials = Trials()
best_trial = fmin(fn=trial_loss, space=space, algo=tpe.suggest, max_evals=50, trials=trials)

100%|██████████| 50/50 [45:43<00:00, 54.87s/trial, best loss: -0.8563927977799835]


In [30]:
# Views the best hyperparameters
best_trial

{'colsample_bytree': 0.5509440040918419,
 'gamma': 0.2749290513553893,
 'learning_rate': 0.055610269598680366,
 'max_depth': 4.0,
 'min_child_weight': 8.0,
 'reg_alpha': 97.43879743549955,
 'reg_lambda': 75.11623552980602,
 'subsample': 0.844084987947726}

In [31]:
del dtrain, dval, y_val, cv_generator

## Submission

In [32]:
# Loads test data set
test = pd.read_csv("../input/tabular-playground-series-oct-2021/test.csv")

# Removes ID column as it is not required for prediction
test.drop(["id"], axis=1, inplace=True)

# Loads submission data set that acts just as a template for submission
submission = pd.read_csv("../input/tabular-playground-series-oct-2021/sample_submission.csv")

**Prepares final XGBoost model with optimized parameters**

In [34]:
# Adds other important parameters
best_trial["max_depth"] = int(best_trial["max_depth"])
best_trial["objective"] = "binary:logistic"
best_trial["eval_metric"] = "auc"
best_trial["tree_method"] = "gpu_hist"

In [43]:
# Gets the model trained over cross validation and predictions 
# against each iteration is stored

test_predictions = []

cv_generator = sk_fold.split(train, y)

dtest = xgb.DMatrix(data=test)

for fold, (idx_train, idx_val) in enumerate(cv_generator):
    print("fold", fold)

    dtrain = xgb.DMatrix(data=train.iloc[idx_train], label=y.iloc[idx_train])
    dval = xgb.DMatrix(data=train.iloc[idx_val], label=y.iloc[idx_val])
    
    model = xgb.train(
        best_trial, 
        dtrain, 
        num_boost_round=2000, 
        evals=[(dtrain, 'train'), (dval, 'eval')],
        early_stopping_rounds=50, verbose_eval=200)
    
    predictions = model.predict(dtest)
    
    test_predictions.append(predictions)
    
    del predictions, model, dval, dtrain

fold 0
[0]	train-auc:0.59823	eval-auc:0.59433
[200]	train-auc:0.84836	eval-auc:0.84682
[400]	train-auc:0.85485	eval-auc:0.85184
[600]	train-auc:0.85810	eval-auc:0.85391
[800]	train-auc:0.86015	eval-auc:0.85494
[1000]	train-auc:0.86164	eval-auc:0.85555
[1200]	train-auc:0.86279	eval-auc:0.85591
[1400]	train-auc:0.86377	eval-auc:0.85612
[1600]	train-auc:0.86462	eval-auc:0.85628
[1800]	train-auc:0.86539	eval-auc:0.85634
[1999]	train-auc:0.86610	eval-auc:0.85639
fold 1
[0]	train-auc:0.59664	eval-auc:0.59901
[200]	train-auc:0.84758	eval-auc:0.84919
[400]	train-auc:0.85414	eval-auc:0.85405
[600]	train-auc:0.85741	eval-auc:0.85602
[800]	train-auc:0.85949	eval-auc:0.85688
[1000]	train-auc:0.86100	eval-auc:0.85732
[1200]	train-auc:0.86217	eval-auc:0.85753
[1400]	train-auc:0.86315	eval-auc:0.85759
[1437]	train-auc:0.86331	eval-auc:0.85761
fold 2
[0]	train-auc:0.59790	eval-auc:0.59533
[200]	train-auc:0.84776	eval-auc:0.84795
[400]	train-auc:0.85424	eval-auc:0.85328
[600]	train-auc:0.85740	eval-auc

In [54]:
test_predictions

[array([0.7308241 , 0.25364307, 0.9059377 , ..., 0.2811955 , 0.5688376 ,
        0.39456698], dtype=float32),
 array([0.75234586, 0.26519367, 0.88730127, ..., 0.27117756, 0.51428294,
        0.46941733], dtype=float32),
 array([0.72856605, 0.25492337, 0.9054919 , ..., 0.33932757, 0.47629607,
        0.41199732], dtype=float32),
 array([0.73929745, 0.2237292 , 0.9052295 , ..., 0.28358278, 0.5110287 ,
        0.37440345], dtype=float32),
 array([0.7509796 , 0.28724867, 0.8912888 , ..., 0.30526415, 0.4860767 ,
        0.38827506], dtype=float32)]

In [48]:
del dtest, cv_generator, test, train

In [55]:
# Predictions stored against each cross validation iteration finally gets aeveraged
# and target column is set with that averaged predictions
submission["target"] = np.mean(np.column_stack(test_predictions), axis=1)

# Checks for sumbission file before saving
submission

id    target
0       1000000  0.740403
1       1000001  0.256948
2       1000002  0.899050
3       1000003  0.850196
4       1000004  0.262870
...         ...       ...
499995  1499995  0.971875
499996  1499996  0.816845
499997  1499997  0.296109
499998  1499998  0.511304
499999  1499999  0.407732

[500000 rows x 2 columns]

In [56]:
# Saves test predictions
submission.to_csv("./submission.csv", index=False)